version: '3'
services:
  web:
    container_name: whist-server
    image: teamwhist/whist-server:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    restart: always
    environment:
      DATABASE_NAME: mongo
  mongo:
    container_name: mongodb
    image: mongo:latest
