name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          platforms: linux/${{ matrix.arch }}
          tags: |
            whist-team/whist-server:${{ matrix.arch }}-test

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
