name: Docker

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  IMAGE_NAME: whist-server

jobs:
  push:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/${{ matrix.arch }}
          tags: |
            teamwhist/whist-server:${{ matrix.arch }}-latest
            teamwhist/whist-server:${{ matrix.arch }}-${{ steps.get_version.outputs.version-without-v }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
