name: Pylint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pin install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint server tests --rcfile=.pylintrc
