name: Pylint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.9 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint sources with flake8
        run: poetry run flake8 whist_server --count --show-source --statistics

      - name: Lint sources with pylint
        run: poetry run pylint whist_server
