name: Upload Python Package

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Whist-Team/actions/setup-poetry@v1
        with:
          python-version: 3.9

      - name: Build project
        run: poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
